#!/bin/bash

function _curl () {
    curl "${@}"
    echo
}

alias curl=_curl
alias ipfs="docker run --rm --net pvs-dev_ipfs peelvalley/ipfs-cli"
alias dagr="docker run --rm  -v/callisto/Data/Phill/_/DA\ Artists:/DA -w /DA phillmac/dagr_revamped dagr.py"
alias dagr-bulk="docker run --rm  -v/callisto/Data/Phill/_/DA\ Artists:/DA -w /DA  phillmac/dagr_revamped:latest  dagr-bulk.py"
alias dagr-utils="docker run --rm -it -v/callisto/Data/Phill/_/DA\ Artists:/DA -w /DA  -v/ananke/D/Source/Phill/Repos/Phill:/Repos dagr-utils.py"
alias dagr-dev="docker run --rm -it -v/callisto/Data/Phill/_/DA\ Artists:/DA -w /DA  -v/ananke/D/Source/Phill/Repos/Phill:/Repos python bash"
