#!/bin/bash

function _curl () {
    curl "${@}"
    echo
}

function curljson () {
    _curl  -H "Content-Type: application/json" "${@}"
}

function curljsonp () {
    _curl  -X POST -H "Content-Type: application/json" "${@}"
}

alias curl=_curl
alias ipfs="docker run --rm --net pvs-dev_ipfs peelvalley/ipfs-cli"
alias dagr="docker run --rm  -v/callisto/Data/Phill/_/DA\ Artists:/DA -w /DA phillmac/dagr_revamped:latest dagr.py"
alias dagr-bulk="docker run --rm  -v/callisto/Data/Phill/_/DA\ Artists:/DA -w /DA  phillmac/dagr_revamped:latest  dagr-bulk.py"
alias dagr-utils="docker run --rm -it -v/callisto/Data/Phill/_/DA\ Artists:/DA -w /DA  -v/ananke/D/Source/Phill/Repos/Phill:/Repos phillmac/dagr_revamped:latest dagr-utils.py"
alias dagr-dev="docker run --rm -it -v/callisto/Data/Phill/_/DA\ Artists:/DA -w /DA  -v/ananke/D/Source/Phill/Repos/Phill:/Repos python bash"
alias orbitdbapi="docker run --rm -it -w /Repos/orbit-db-http-api  -v pvs-dev_cert-data:/certs -v/ananke/D/Source/Phill/Repos/Phill:/Repos --net pvs-dev_ipfs node:11.13 bash"
