#!/bin/bash

function source_env_files () {
    local repos_dir
    repos_dir="${REPOS_DIR:-${HOME}/source/repos}"

    local repo_dirs_list=(
            "kapcd/Dev-Env"
            "pvs/Dev-Env"
            "pvs/Build-Env"
            "phill/Dev-Env"
            "pvte/Dev-Env"
            "pvte/Prod-Env"
            "scouts/Dev-Env",
            "epra/Dev-Env"
            )

    for repo in "${repo_dirs_list[@]}"; do
        local scripts_dir
        scripts_dir="${repos_dir}/${repo}"/Scripts
        [[ "${DOCKERENV_DEBUG}" ]] && {
            echo "Searching for ${scripts_dir}"
        }
        [[ -d "${repos_dir}/${repo}/Scripts" ]] && {
            [[ "${DOCKERENV_DEBUG}" ]] && {
                echo "Found ${scripts_dir}"
            }
            for file in  "${repos_dir}/${repo}"/Scripts/*functions.sh
            do
            [[ "${DOCKERENV_DEBUG}" ]] && {
                echo "Sourcing ${file}"
            }
            source "${file}"
            done
        }
    done


    local hostname
    hostname=$(hostname)
    case "${hostname}" in
        'charon' )
            alias_pvs_dev_charon
            alias_pvs_dev_update
            #alias_pvs_build_charon
            #alias_pvs_build_update
            #alias_kapcd_dev_charon
            #alias_kapcd_dev_update
            alias_phill_dev_charon
            alias_phill_dev_update
            ;;
        'kore' )
            alias_pvs_dev_kore
            alias_pvs_dev_update
            alias_pvs_build_kore
            alias_pvs_build_update
            alias_kapcd_dev_kore
            alias_kapcd_dev_update
            alias_phill_dev_kore
            alias_phill_dev_update
            alias_pvte_dev_kore
            alias_pvte_dev_update
            alias_scouts_dev_update
            alias_scouts_dev_kore
            alias_epra_dev_update
            alias_epra_dev_kore
            ;;
        'atlas' )
            alias_phill_dev_atlas
            alias_phill_dev_update
            ;;
        'hughes' )
            alias_pvte_prod_hughes
            alias_pvte_prod_update
            ;;

        'vps1' )
            alias_phill_dev_vps1
            alias_phill_dev_update
            ;;
        'vps2' )
            alias_phill_dev_vps2
            alias_phill_dev_update
            ;;
        'vps3' )
            alias_phill_dev_vps3
            alias_phill_dev_update
            ;;
        *)
            echo "Unkown host ${hostname}"
            ;;
    esac
}

source_env_files
