#!/bin/bash

function source_env_files () {
    local repos_dir
    repos_dir="${REPOS_DIR:-${HOME}/source/repos}"



    #set up docker & compose aliases
    for file in  ${repos_dir}/pvs/Dev-Env/Scripts/*
    do
        source "${file}"
    done

    alias_pvs_dev_kore
    alias_pvs_dev_update

    for file in  ${repos_dir}/pvs/Build-Env/Scripts/*
    do
        source "${file}"
    done

    alias_pvs_build_kore
    alias_pvs_build_update

    for file in  ${repos_dir}/kapcd/Dev-Env/Scripts/*functions.sh
    do
        source "${file}"
    done

    alias_kapcd_dev_kore
    alias_kapcd_dev_update

    for file in  ${repos_dir}/phill/Dev-Env/Scripts/*functions.sh
    do
      source "${file}"
    done

    alias_phill_dev_kore
    alias_phill_dev_update


    for file in  ${repos_dir}/pvte/Dev-Env/Scripts/*functions.sh
    do
      source "${file}"
    done

    for file in  ${repos_dir}/pvte/Prod-Env/Scripts/*functions.sh
    do
      source "${file}"
    done

    case "$(hostname)" in
        'kore' )
            alias_pvte_dev_kore
            alias_pvte_dev_update
            ;;
        'hughes' )
            alias_pvte_prod_huges
            ;;

    esac
}

source_env_files
