#!/bin/bash

function source_env_files () {
    local repos_dir
    repos_dir="${REPOS_DIR:-${HOME}/source/repos}"

    local repo_dirs_list=(
            "kapcd/Dev-Env"
            "pvs/Dev-Env"
            "pvs/Build-Env"
            "phill/Dev-Env"
            "pvte/Dev-Env"
            "pvte/Prod-Env"
            "scouts/Dev-Env"
            )

    for repo in "${repo_dirs_list[@]}"; do
        [[ -d "${repos_dir}/${repo}/Scripts" ]] && \
        for file in  "${repos_dir}/${repo}"/Scripts/*functions.sh
        do
        source "${file}"
        done
    done



    case "$(hostname)" in
        'kore' )
            alias_pvs_dev_kore
            alias_pvs_dev_update
            alias_pvs_build_kore
            alias_pvs_build_update
            alias_kapcd_dev_kore
            alias_kapcd_dev_update
            alias_phill_dev_kore
            alias_phill_dev_update
            alias_pvte_dev_kore
            alias_pvte_dev_update
            alias_scouts_dev_update
            alias_scouts_dev_kore
            ;;
        'titan' )
        alias_phill_dev_titan
        ;;
        'hughes' )
            alias_pvte_prod_hughes
            alias_pvte_prod_update
            ;;
    esac
}

source_env_files
