#!/bin/bash
shorthost=$(cut -d"." -f1 <<<"$HOSTNAME")
shorthost_lower=${shorthost,,}
BASH_RC_DIR="${HOME}/.bashrc.d"
BASH_RC_HOST_DIR="${HOME}/.bashrc.d/${shorthost_lower}.bashrc.d"

[[ "${HOSTENV_DEBUG}" ]] && {
    echo "Searching for ${BASH_RC_HOST_DIR}" >&2
}
[[ -d "${BASH_RC_HOST_DIR}" ]] && {
    [[ "${HOSTENV_DEBUG}" ]] && {
    echo "Found ${BASH_RC_HOST_DIR}" >&2
    }
    for file in "${BASH_RC_HOST_DIR}"/*
    do
        [[ "${HOSTENV_DEBUG}" ]] && {
                echo "Sourcing ${file}"
        }
        source "${file}"
    done
}

export BASH_RC_DIR
export BASH_RC_HOST_DIR
