#!/bin/bash
shorthost=$(cut -d"." -f1 <<<"$HOSTNAME")
BASHRCDIR="${HOME}/.bashrc.d/${shorthost}.bashrc.d"

[[ "${HOSTENV_DEBUG}" ]] && {
    echo "Searching for ${BASHRCDIR}" >&2
}
[[ -d "${BASHRCDIR}" ]] && {
    [[ "${HOSTENV_DEBUG}" ]] && {
    echo "Found ${BASHRCDIR}" >&2
    }
    for file in "${BASHRCDIR}"/*
    do
        [[ "${HOSTENV_DEBUG}" ]] && {
                echo "Sourcing ${file}"
        }
        source "${file}"
    done
}

export BASHRCDIR
