#! /bin/bash

function ipfs.get.recursive () {
    local itemhash
    local itempath
    while read -r itemhash itempath
    do
        echo "$(date) Fetching ${itempath}" >&2
        curl -s "${IPFS_HTTP_GATEWAY}/ipfs/${itemhash}" > /dev/null
    done < <(ipfs.ls.recursive "${*}")
}

function ipfs.ls.recursive () {
    local entries
    local itemtype
    local itemhash
    local itemname

    echo "$(date) Resolving ${*}" >&2
    entries=$(ipfs.ls "${*}" | ipfs.links.info)
    while read -r itemtype itemhash itemname
    do
        echo "${itemhash}" "${1}/${itemname}"
        if (( itemtype == 1))
        then
            ipfs.ls.recursive "${1}/${itemname}"
        fi
    done <<< "${entries}"
}

function ipfs.ls () {
    local addr
    local addr_encoded
    local url
    local result

    addr=${1:-$IPFS_ADDR}

    if [[ -z "${addr}" ]];
    then
        echo "IPFS addr is required" >&2
        return 252
    fi

    addr_encoded=$(rawurlencode "${addr}")

    [[ -n "${IPFS_DEBUG}" ]] &&  echo "addr_encoded is ${addr_encoded}" >&2

    url="${IPFS_HTTP_GATEWAY}/${IPFS_API}/ls?arg=${addr_encoded}"
    [[ -n "${IPFS_DEBUG}" ]] &&  echo "url is ${url}" >&2

    result=$(curl "${url}")

    jq -r ".Objects[].Links" <<< "${result}"
}

function ipfs.links.info () {
    # shellcheck disable=SC2006,SC2154,SC2086
    jsawk "'return [this.Type,  this.Hash, this.Name].join(String.fromCharCode(32))'" -a "'return this.join(String.fromCharCode(10))'"
}

function ipfs.pin.ls () {
    ipfs pin ls | grep -v indirect | cut -f 1 -d " " | sort > pins.txt
}

function ipfs.pins.prune () {
    local pinHash
    local resp
    local total
    local pcount

    test -f inp || mkfifo inp

    total=$(wc -l < pins.txt)
    pcount=1

    while read -r pinHash
    do
        echo "Hash is ${pinHash} [${pcount}/${total}]"
        ipfs ls "${pinHash}"
        resp=$(<inp)
        [[ "${resp}" == "q" ]] && return
        [[ "${resp}" == "y" ]] && ipfs pin rm "${pinHash}"
        ((pcount++))
    done < pins.txt
}

function ipfs.pins.details () {
    local pinHash
    local resp
    local total
    local pcount

    total=$(wc -l < pins.txt)
    pcount=1

    while read -r pinHash
    do
        echo "Hash is ${pinHash} [${pcount}/${total}]"
        ipfs ls "${pinHash}"
        ((pcount++))
    done < pins.txt | tee pins.details.txt
}

function check_lockout_time () {
    local currenttime

    if [[ -z  "${IPFS_PIN_ALLOWED_START}" ]] || [[ -z "${IPFS_PIN_ALLOWED_FIN}" ]]
    then
        return 0
    fi

    currenttime=$(date +%H:%M)

    if [[ "${currenttime}" > "${IPFS_PIN_ALLOWED_START}" ]] || [[ "${currenttime}" < "${IPFS_PIN_ALLOWED_FIN}" ]]
    then
        return 0
    fi

    return 1
}

function ipfs.pin.monitor () {
    local currenttime
    local rlast
    local ipns
    local rnew
    local pin_timeout
    local resolve_timeout
    local sleep_delay
    ipns=${1:-$IPFS_PIN_HASH}
    pin_timeout=${2:-$IPFS_PIN_TIMEOUT}
    resolve_timeout=${3:-$IPFS_RESOLVE_TIMEOUT}
    sleep_delay=${4:-$IPFS_PIN_SLEEP}

    if [[ -z "${ipns}" ]]
    then
        echo "ipns addr is required"
        return 252
    fi
    while true
    do
        if rnew=$(ipfs resolve --timeout "${resolve_timeout}" "${ipns}")
        then
            if ! check_lockout_time || [[ "${rlast}" == "${rnew}" ]]
            then
                sleep "${sleep_delay}"
                continue
            fi
            echo "Pinning ${rnew}"

            if ipfs pin add --progress --timeout "${pin_timeout}" "${rnew}"
            then
                if [[ -n "${rlast}" ]]
                then
                    echo "Removing pin for ${rlast}"
                    ipfs pin rm "${rlast}"
                fi
                rlast=${rnew}
            fi
            date
        fi
    done
}

export -f ipfs.ls
export -f ipfs.ls.recursive
export -f ipfs.get.recursive
export -f ipfs.pins.prune
export -f ipfs.pin.monitor

IPFS_API="api/v0"

export IPFS_API