#!/bin/bash


function db.open () {
    local host
    local dbAddr

    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    curljsonp -d "{\"awaitOpen\": false, \"fetchEntryTimeout\": ${ORBIT_DB_ENTRIES_TIMEOUT}}" "${host}/db/${dbAddr}" | python -m json.tool
}

function db.close () {
    local host
    local dbAddr

    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl -X DELETE "${host}/db/${dbAddr}"
}

function orbitdb.pending () {
    local dbAddr

    host=${1:-${ORBIT_DB_HOST}}

    _curl "${host}/pending"
}

function db.load () {
    local host
    local dbAddr

    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl -X POST "${host}/db/${dbAddr}/load"
}

function db.all () {
    local host
    local dbAddr

    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl "${host}/db/${dbAddr}/all" | python -m json.tool
}

function db.get () {
    local host
    local dbAddr

    host=${3:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${2}")

    _curl "${host}/db/${dbAddr}/${1}" | python -m json.tool
}

function db.put () {
    local host
    local dbAddr

    host=${3:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${2}")

    curljsonp -d "[${*:1:1}]" "${host}/db/${dbAddr}/put"
}

function db.sync () {
    local host
    local dbAddr


    host=${3:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${2}")

    curljsonp -d "[${*:1:1}]" "${host}/db/${dbAddr}/sync"
}

function db.replication () {
    local host
    local dbAddr


    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl "${host}/db/${dbAddr}" |  jsawk "'return this.replicationStatus'" | python -m json.tool
}


function db.status () {
    local host
    local dbAddr


    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl "${host}/db/${dbAddr}" |  jsawk "'return {loaded: this.loaded, ready: this.ready}'" | python -m json.tool


}

function db.info () {
    local host
    local dbAddr


    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl "${host}/db/${dbAddr}" | python -m json.tool
}

function db.oplog.heads () {
    local host
    local dbAddr


    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl "${host}/db/${dbAddr}/oplog/heads" | python -m json.tool
}


function db.oplog.values () {
    local host
    local dbAddr


    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl "${host}/db/${dbAddr}/oplog/values" | python -m json.tool
}

function db.oplog.values.hashes () {
    local host
    local dbAddr


    host=${2:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${1}")

    _curl "${host}/db/${dbAddr}/oplog/values" | jsawk "'return this.hash'" -a "'return this.join(\" \")'"
}

function db.heads.pin () {
    declare -a hashes=()
    for hash in $(db.oplog.values.hashes "${@}")
    do
        hashes+=("$hash")
        if [[ ${#hashes[@]} -ge ${IPFS_PIN_BATCH_COUNT} ]]; then
            echo "Pinning ${hashes[*]}"
            ipfs pin add --progress --timeout "${IPFS_PIN_TIMEOUT}" "${hashes[@]}"
            hashes=()
            sleep 30
        fi
    done
    # Pin leftover hashes batch < 100
    echo "Pinning ${hashes[*]}"
    ipfs pin add --progress --timeout "${IPFS_PIN_TIMEOUT}" "${hashes[@]}"
}

function db.events () {
    local host
    local dbAddr
    local events


    host=${3:-${ORBIT_DB_HOST}}

    dbAddr=$(rawurlencode "${2}")

    events=$(rawurlencode "${1}")

    _curl "${host}/db/${dbAddr}/events/${events}"
}

export -f db.open
export -f db.close
export -f orbitdb.pending
export -f db.load
export -f db.all
export -f db.get
export -f db.put
export -f db.sync
export -f db.replication
export -f db.status
export -f db.info
export -f db.oplog.heads
export -f db.oplog.values
export -f db.oplog.values.hashes
export -f db.heads.pin
export -f db.events

